AllCops:
  RunRailsCops: true

AlignParameters:
  EnforcedStyle: with_fixed_indentation

Documentation:
  Enabled: false

MethodLength:
  Max: 5

StringLiterals:
  EnforcedStyle: double_quotes

TrailingComma:
  EnforcedStyleForMultiline: comma
