call plug#begin()
if !has('nvim')
  Plug 'tpope/vim-sensible'
  Plug 'tmux-plugins/vim-tmux-focus-events' " makes autoread work
endif
Plug 'tpope/vim-vinegar' " better netrw
Plug 'tpope/vim-sleuth' " heuristically detected indent
Plug 'tpope/vim-rsi' " readline/emacs style insertion
Plug 'tpope/vim-eunuch' " UNIX helpers :Mkdir :Rename
Plug 'tpope/vim-unimpaired' " ]b [b
Plug 'tpope/vim-commentary' " gc gcc
Plug 'tpope/vim-surround' " ys cs ds S
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-endwise' " auto close statements
Plug 'tpope/vim-fugitive' " git helpers
Plug 'tommcdo/vim-lion' " alignment gl gL
Plug 'AndrewRadev/splitjoin.vim' " gS gJ

Plug 'sickill/vim-monokai'
Plug 'bling/vim-airline'
" Plug 'tpope/vim-flagship'
" Plug 'itchyny/lightline.vim'
Plug 'airblade/vim-gitgutter'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'roxma/vim-tmux-clipboard'

Plug 'scrooloose/syntastic'
Plug 'vim-ruby/vim-ruby', { 'for': 'ruby' }
Plug 'derekwyatt/vim-scala', { 'for': 'scala' }
Plug 'derekwyatt/vim-sbt', { 'for': 'sbt.scala' }
Plug 'saltstack/salt-vim', { 'for': 'sls' }
" Plug 'mustache/vim-mustache-handlebars'
Plug 'elixir-lang/vim-elixir', { 'for': 'elixir' }
" Plug 'rust-lang/rust.vim'
Plug 'ElmCast/elm-vim', { 'for': 'elm' }
Plug 'venantius/vim-cljfmt', { 'for': 'clojure' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }
" Plug 'tpope/vim-salve', { 'for': 'clojure' }
" Plug 'guns/vim-clojure-static', { 'for': 'clojure' }
Plug 'dag/vim-fish', { 'for': 'fish' }
call plug#end()

colorscheme monokai

if has("mouse") | set mouse=a | endif

set autowrite " write when switching buffers
set colorcolumn=80,120
set cursorline
set foldlevelstart=99 " open folds by default
set foldmethod=syntax
set hlsearch
set ignorecase smartcase " case-sensitive if search has upper-case characters
set lazyredraw
set list listchars=tab:▸\ ,trail:·,nbsp:␣,extends:>,precedes:< showbreak=↪ 
set nobackup
set noswapfile
set splitbelow
set splitright
set tags=.tags " use hidden tags file
set undofile undodir=/tmp " persist undo history
set visualbell

noremap <leader>R :source $MYVIMRC<cr>
noremap <leader>E :tabedit $MYVIMRC<cr>
noremap <F6> :set invspell<cr>
noremap <c-l> :noh<cr>
map <leader>- -:bd#<cr>

inoremap <c-s> <esc>:w<cr>
noremap <c-s> <esc>:w<cr>

map <space> <leader>
map <space><space> <leader><leader>

call denite#custom#var('file_rec', 'command',
      \ ['rg', '--files', '--glob', '!.git', ''])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts',
      \ ['--hidden', '--vimgrep', '--no-heading', '-S'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])

call denite#custom#map('insert', '<c-j>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<c-k>', '<denite:move_to_previous_line>', 'noremap')
call denite#custom#map('insert', '<c-n>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<c-p>', '<denite:move_to_previous_line>', 'noremap')
call denite#custom#map('insert', '<c-h>', '<denite:toggle_select_down>', 'noremap')

call denite#custom#option('default', {
        \ 'auto_resize': 'true',
        \ 'highlight_matched_char': 'Normal',
        \ 'highlight_matched_range': 'Normal',
        \ 'highlight_mode_insert': 'Search',
        \ 'highlight_mode_normal': 'IncSearch',
        \ 'prompt': '❯',
        \ 'winheight': '5',
        \ 'winminheight': '3',
        \ })

nnoremap <leader><leader> :Denite file_rec<cr>
nnoremap <leader>b :Denite buffer<cr>
nnoremap <leader>g :Denite grep:. -mode=normal<cr>
nnoremap <leader>8 :DeniteCursorWord grep:. -mode=normal<cr>
vnoremap <leader>8 "*y:Denite grep:. -mode=normal<cr>
nnoremap <leader>d :DeniteBufferDir file_rec<cr>
nnoremap <leader>o :Denite outline -mode=normal<cr>
nnoremap <leader>h :Denite help<cr>
nnoremap <leader>r :Denite register<cr>

let g:airline#extensions#tabline#enabled = 1

let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
au VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=NONE
au VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=0
